# Generated by Django 5.2.5 on 2025-09-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=256, null=True)),
                ('root_cause', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('assign_team', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
